### ISSUE TITLE
I like origin one to put hint at the end, can you supported it? 

### ISSUE THREAD

**Issue by Decodetalkers** [MysticalDevil/inlay-hints.nvim#1]
https://github.com/lvimuser/lsp-inlayhints.nvim/

I like this plugin very much, like the hints be put to the end. but it is unmaintained any more. 

your plugin is very good, thanks for your efforts!!

**Comment by MysticalDevil** [comment]
Thanks for your support. This plugin is actually very simple. I Just wrote in the document how to enable the inlay hint os each LSP.
