### ISSUE TITLE
Can you update for pyright and basedpyright setup?

### ISSUE THREAD

**Issue by PyDataBlog** [MysticalDevil/inlay-hints.nvim#2]
These 2 language servers are hugely popular so would be helpful to have the docs updated for them, I think.

**Comment by MysticalDevil** [comment]
The official version of Pyright does not support inlay hints. However, basedpyright, when enabled with the official inlay hints feature, automatically activates without requiring any special configuration.

69e599ebf9f08afb0bb651c2849e88895b080af2 have add the description.
