### ISSUE TITLE
how can enable it for vtsls?

### ISSUE THREAD

**Issue by realtica** [MysticalDevil/inlay-hints.nvim#4]
Please, I can't enable it for [vtsls](https://github.com/yioneko/vtsls)

**Comment by MysticalDevil** [comment]
Sorry, I don't know. I can try to find out how to turn it on.

**Comment by lucioreyli** [comment]
> Please, I can't enable it for [vtsls](https://github.com/yioneko/vtsls)

Yeah, it's working very well
![CleanShot 2024-07-05 at 17 43 14](https://github.com/MysticalDevil/inlay-hints.nvim/assets/62335491/e7ed4b7d-1acf-4b48-a9bd-402a33c33c4b)

You can use the same config from `Svelte`, but changing for `vtsls`:
```lua
require('lspconfig').vtsls.setup {
  -- capabilities = capabilities,
  -- flags = lsp_flags,
  -- on_attach = on_attach,
  settings = {
    typescript = {
      inlayHints = {
        parameterNames = { enabled = 'all' },
        parameterTypes = { enabled = true },
        variableTypes = { enabled = true },
        propertyDeclarationTypes = { enabled = true },
        functionLikeReturnTypes = { enabled = true },
        enumMemberValues = { enabled = true },
      },
    },
  },
}
```

**Comment by MysticalDevil** [comment]
> > Please, I can't enable it for [vtsls](https://github.com/yioneko/vtsls)请，我无法为 vtsls 启用它
> 
> Yeah, it's working very well是的，效果很好 ![CleanShot 2024-07-05 at 17 43 14](https://private-user-images.githubusercontent.com/62335491/346229325-e7ed4b7d-1acf-4b48-a9bd-402a33c33c4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMjQxMTMsIm5iZiI6MTcyMDIyMzgxMywicGF0aCI6Ii82MjMzNTQ5MS8zNDYyMjkzMjUtZTdlZDRiN2QtMWFjZi00YjQ4LWE5YmQtNDAyYTMzYzMzYzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIzNTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZTg2NmMzZjE1NmU3ZGNmMDI3NmI0NWE1NTdkYjQzZGJmZjk5M2I1OWNkY2E3M2ZiYjM0NGNlYjYyMjlmZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0G9pn9Bx1513tHDu_YjxPIJD6DUsOijCyH6ALWZNw_0)
> 
> You can use the same config from `Svelte`, but changing for `vtsls`:您可以使用 `Svelte` 中的相同配置，但对 `vtsls` 进行更改：
> 
> ```lua
> require('lspconfig').vtsls.setup {
>   -- capabilities = capabilities,
>   -- flags = lsp_flags,
>   -- on_attach = on_attach,
>   settings = {
>     typescript = {
>       inlayHints = {
>         parameterNames = { enabled = 'all' },
>         parameterTypes = { enabled = true },
>         variableTypes = { enabled = true },
>         propertyDeclarationTypes = { enabled = true },
>         functionLikeReturnTypes = { enabled = true },
>         enumMemberValues = { enabled = true },
>       },
>     },
>   },
> }
> ```

Thanks for your contribution. I will add it into the document.
