### ISSUE TITLE
how to setup dart files?

### ISSUE THREAD

**Issue by xinghe98** [MysticalDevil/inlay-hints.nvim#5]
thanks for creation,how can i setup dart file?

**Comment by MysticalDevil** [comment]
Sorry, I didn't find the inlay hints option in the official documentation of dartls. But you can refer to my configuration file.[https://github.com/MysticalDevil/nvim/blob/master/lua/devil/lsp/config/dartls.lua](url)

**Comment by xinghe98** [comment]
thanks.  I have a question and want to ask, when i set [vim.lsp.inlay_hints.enable()] in dart file’s cmdline, inlay
 Hint was Effective. But,when I set [vim.lsp.inlay_hints.enable()] in lsp config or other config files, it doesn’t work.

**Comment by MysticalDevil** [comment]
Because some LSP inlay hints need to be turned on manually, for example, LuaLS need to be turned on with the following option
```lua
require("lspconfig").lua_ls.setup({
  settings = {
    Lua = {
      hint = {
        enable = true, -- necessary
      }
    }
  }
})
```

**Comment by xinghe98** [comment]
thank you
