### ISSUE TITLE
where is the configuration options available?

### ISSUE THREAD

**Issue by samarth-na** [MysticalDevil/inlay-hints.nvim#9]
i cant seem to find them sorry if its just skill issue on my part

**Comment by MysticalDevil** [comment]
The configuration options are, in fact, minimally influential. This project primarily serves as a consolidated resource demonstrating how to activate inlay hints across different LSPs.

**Comment by MysticalDevil** [comment]
After configuring the plugin, you also need to enable the relevant LSP configuration for enabling inlay hints (using the nvim-lspconfig plugin).
